exports.featureList = [
  { name: 'sunroof', price: 1000 },
  { name: 'leather seats', price: 15000 },
  { name: 'heated seats', price: 8000 },
  { name: 'backup camera', price: 5000 },
  { name: 'bluetooth', price: 3000 },
  { name: 'keyless entry', price: 4000 },
  { name: 'remote start', price: 6000 },
  { name: 'adaptive cruise control', price: 12000 },
  { name: 'lane departure warning', price: 10000 },
  { name: 'navigation system', price: 15000 },
  { name: 'parking sensors', price: 7000 },
  { name: 'blind spot monitoring', price: 8000 },
  { name: 'automatic parking', price: 20000 },
  { name: 'carplay', price: 5000 },
  { name: 'android auto', price: 5000 },
  { name: 'premium sound system', price: 25000 },
  { name: 'aerodynamic Kit', price: 25000 },
];
