module.exports = {
  USER_NOT_FOUND: 'User not found',
  CAR_NOT_FOUND: 'Car not found',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden. Admin access required',
  ALREADY_EXISTS: 'Username/Email already exists',
  INVALID_ID: 'Invalid ID',
  USER_NOT_UPDATED: 'User not updated',
  USER_NOT_DELETED: 'User not deleted',
  USER_NOT_CREATED: 'User not created',
  USER_DELETED: 'User deleted successfully',
  USER_UPDATED: 'User updated successfully',
  LOGGED_OUT: 'User logged out successfully',
  NO_SEARCH_QUERY: 'No search query',
  CAR_ALREADY_EXISTS: 'Car already exists',
  CAR_NOT_CREATED: 'Car not created',
  CAR_NOT_UPDATED: 'Car not updated',
  SOME_ERROR: 'Some error occured. Try again later',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  NO_RESULTS: 'No results found',
  INSUFFICIENT_BALANCE: 'Insufficient balance in your wallet',
  CAR_OUT_OF_STOCK: 'Car is out of stock',
  FAILED_TO_FETCH_CAR: 'Failed to fetch car details',
  FAILED_TO_UPDATE_USER: 'Failed to update user',
  FAILED_TO_UPDATE_CAR: 'Failed to update car quantity',
  FAILED_TO_SAVE_INVOICE: 'Failed to save invoice',
  FAILED_TO_GENERATE_INVOICE: 'Failed to generate invoice',
  NO_INVOICES: 'No invoices found',
  INVOICE_NOT_FOUND: 'Invoice not found',
  NO_USER_INVOICES: 'No invoices found for this user',
  FAILED_TO_SAVE_PAYMENT: 'Failed to save payment',
  INVALID_PAYMENT: 'Invalid payment details',
  PAYMENT_NOT_FOUND: 'Payment not found',
  PAYMENT_PENDING: 'Payment is pending',
  INVALID_APPOINTMENT: 'Invalid appointment details',
  APPOINTMENT_NOT_CREATED: 'Appointment not created',
  FAILED_TO_SAVE_APPOINTMENT: 'Failed to save appointment',
  APPOINTMENT_NOT_FOUND: 'Appointment not found',
  APPOINTMENT_NOT_CANCELED: 'Appointment not canceled',
  NO_APPOINTMENTS_FOUND: 'No Appointments found',
  SLOT_NOT_AVAILABLE: 'Slot not available',
};
