module.exports = {
  USER_NOT_FOUND: 'User not found',
  CAR_NOT_FOUND: 'Car not found',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden. Admin access required',
  ALREADY_EXISTS: 'Username/Email already exists',
  INVALID_ID: 'Invalid ID',
  USER_NOT_UPDATED: 'User not updated',
  USER_NOT_DELETED: 'User not deleted',
  USER_DELETED: 'User deleted successfully',
  USER_UPDATED: 'User updated successfully',
  LOGGED_OUT: 'User logged out successfully',
  NO_SEARCH_QUERY: 'No search query',
  CAR_ALREADY_EXISTS: 'Car already exists',
  CAR_NOT_CREATED: 'Car not created',
  CAR_NOT_UPDATED: 'Car not updated',
  DATA_NOT_VALID: 'Data is not valid',
  INVALID_CREDENTIALS: 'Invalid Credentials',
  NO_RESULTS: 'No results found',
};
